Topbar
wolox-training/mg-react pull request #21
Opened 2019-07-25 17:18 UTC by josepplloo

## Summary

Navigation bar added
## Screenshots

![topbar](https://user-images.githubusercontent.com/1114740/61894444-12040b00-aed6-11e9-9e1b-bdcfb8e413e2.gif)

## Trello Card
https://trello.com/c/BBvHRHVy/24-routing-ii-topbar

2019-07-25 23:35 UTC, CrisVega08 requested changes

2019-07-25 23:35 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/screens/Podium/index.js
> +    <div className={styles.container}>
If you use this div inside of Matches component you can remove podium and use Matches.

2019-07-25 23:35 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/screens/Podium/styles.module.scss
> + display: flex;
Here review the tab size.

2019-07-25 23:35 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/AppRouter/components/AuthInfo/styles.module.scss
> +  overflow:auto;
Add space here.

2019-07-25 23:35 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/AppRouter/components/AuthInfo/styles.module.scss
> +  margin: 0 5px;
sort it.

2019-07-26 17:24 UTC, josepplloo commented on react/tic-tac-toe/src/app/components/AppRouter/components/AuthInfo/styles.module.scss
> +  margin: 0 5px;
IDK what happen with that file (Don't update)

2019-07-26 18:02 UTC, CrisVega08 requested changes

2019-07-26 18:02 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/screens/Podium/index.js
> +class Podium extends Component {
If you change the name of component change also file name.

2019-07-29 15:06 UTC, josepplloo commented on react/tic-tac-toe/src/app/screens/Podium/index.js
> +class Podium extends Component {
Would you like me to change this name (use Matches label in app instead of Podium) ?

2019-07-29 18:19 UTC, CrisVega08 approved these changes
Only change folder name, nice work

2019-07-29 18:19 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/screens/Podium/index.js
> +class Podium extends Component {
Yes, but i refer to name of folder that this Component, look that folder has name Matches change to Podium.
! [image] (https://user-images.githubusercontent.com/26824183/62071967-3e37c880-b203-11e9-9fb7-7a1c85343160.png)

2019-07-29 19:43 UTC, merged