Recompose
wolox-training/mg-react pull request #22
Opened 2019-07-25 20:38 UTC by josepplloo

## Summary

 - Recompose library implemented.

## Screenshots

![recompose](https://user-images.githubusercontent.com/1114740/61906475-0c67ee80-aef1-11e9-9ebf-66ed22b33bf2.gif)

## Trello Card

https://trello.com/c/iaR1lg1R/16-redux-iv-redux-recompose

2019-07-26 20:57 UTC, CrisVega08 requested changes

2019-07-26 20:57 UTC, CrisVega08 commented on react/tic-tac-toe/src/redux/login/actions.js
> +        dispatch({
Here you can do something like ---> ```dispatch(actionsCreator.setauth(response.data))```

2019-07-26 20:57 UTC, CrisVega08 commented on react/tic-tac-toe/src/redux/login/actions.js
>    setauth: token => ({ type: actions.LOGIN_SUCCESS, payload: token }),
Change this name to camelCase

2019-07-26 20:57 UTC, CrisVega08 commented on react/tic-tac-toe/src/redux/login/actions.js
> +        dispatch({ type: actions.LOGIN_FAILURE, payload: response });
I don't know why do you send payload when login failed?, to me if you don't show a message error from backend you should be set a state that show error property on true.

2019-07-26 20:57 UTC, CrisVega08 commented on react/tic-tac-toe/src/redux/login/reducer.js
> +  isLoggedIn: null,
What is the difference between isLoggedIn and is Auth??

2019-07-26 20:57 UTC, CrisVega08 commented on react/tic-tac-toe/src/redux/login/reducer.js
> +const reducerDescription = {
Here try to use primaryActions and override properties show this 👀 https://github.com/Wolox/redux-recompose/tree/master/src/completers/completeReducer

2019-07-29 15:47 UTC, josepplloo commented on react/tic-tac-toe/src/redux/login/reducer.js
> +  isLoggedIn: null,
At the moment I have this:
```
const initialState = {
  isLogged: false, \\ for the error message of wrong credentials
  isAuth: false \\ for authorize the user and show the others views, in this case the credentials are correct
};
```

2019-07-29 18:06 UTC, josepplloo commented on react/tic-tac-toe/src/redux/login/reducer.js
> +const reducerDescription = {
For sure a great change

2019-07-30 17:52 UTC, CrisVega08 requested changes

2019-07-30 17:52 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/AppRouter/components/AuthInfo/index.js
> +  if (onError) {
change it for a if() else if ()

2019-07-30 17:52 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/AppRouter/components/AuthInfo/styles.module.scss
Delete it

2019-07-30 17:52 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/AppRouter/components/AuthRoute/index.js
> +    return islogged ? <Redirect from="/login" to="/game" /> : <Login onSubmit={this.handleSubmit} />;
Remember that you have constants for Routes

2019-07-30 17:52 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/AppRouter/index.js
> +  setAuth: func,
Someone of these props are required??

2019-07-31 15:38 UTC, CrisVega08 approved these changes

2019-07-31 15:38 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/screens/Game/styles.module.scss
> +    color: white;
Use a variable here

2019-07-31 15:38 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/screens/Podium/index.js
> +  state = {
In next pr you will change this for store.

2019-07-31 15:38 UTC, CrisVega08 commented on react/tic-tac-toe/src/services/MatchesService.js
> +      .then(response => response.data)
This change on next pr.

2019-07-31 16:46 UTC, josepplloo commented on react/tic-tac-toe/src/app/screens/Podium/index.js
> +  state = {
Yes Sir

2019-07-31 20:33 UTC, merged