Hoc
wolox-training/mg-react pull request #23
Opened 2019-07-30 14:36 UTC by josepplloo

## Summary

- hoc added.

## Screenshots

![hoc](https://user-images.githubusercontent.com/1114740/62138375-29b00a80-b2ad-11e9-8c1b-377a4c086aab.gif)

## Trello Card

https://trello.com/c/DMfTomzB/19-patterns-ii-hocs

2019-07-30 22:41 UTC, CrisVega08 requested changes
Jose this pr has conflicts solve please.

2019-08-01 15:32 UTC, CrisVega08 requested changes

2019-08-01 15:32 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/AppRouter/components/AuthInfo/styles.module.scss
> +    width: 91px;
90px

2019-08-01 15:32 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/AppRouter/components/AuthInfo/styles.module.scss
> +    margin: 0 0 10px 0;
margin-botom: 10px;

2019-08-01 15:32 UTC, CrisVega08 commented on react/tic-tac-toe/src/redux/matches/reducer.js
> +  primaryActions: [actions.MATCHES]
Beautiful ❤️

2019-08-01 15:32 UTC, CrisVega08 commented on react/tic-tac-toe/src/redux/matches/actions.js
> +export const actions = createTypes(completeTypes(['MATCHES']), '@@MATCHES');
👏

2019-08-01 15:32 UTC, CrisVega08 commented on react/tic-tac-toe/src/redux/game/actions.js
> +  onClick: (id, history, stepNumber, xIsNext) => dispatch => {
This don't like, the onClick method have more mean on component

2019-08-01 15:32 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/AppRouter/components/AuthInfo/styles.module.scss
> +  &::before {
almost every psuedo elements have similar properties use a extends something like 
```%base-psuedo { ... } ```

2019-08-01 15:32 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/AppRouter/index.js
> +import Spinner from 'react-spinkit';
The main idea for loader is made create a HOC that wrapper the component not put a spinner. 💀 💀 💀 💀

2019-08-01 15:32 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/screens/Game/index.js
> -  calculateWinner = squares => {
If prefer you use this here I only send the action when the winner exist.

2019-08-01 15:32 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/screens/Game/styles.module.scss
>      padding: 1rem;
we usually don't use rem try with prixels

2019-08-01 15:32 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/screens/Podium/index.js
> -  state = {
👏

2019-08-01 22:30 UTC, CrisVega08 requested changes

2019-08-01 22:30 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/AppRouter/components/AuthInfo/styles.module.scss
> +    top: 28px;
order properties

2019-08-01 22:30 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/AppRouter/index.js
> +  onLoading: store.auth.isloginLoading
Delete it prop.

2019-08-01 22:30 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/hocs/index.js
> +function higherOrderComponent(WrappedComponent) {
Change this name for something that describe function.

2019-08-01 22:30 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/components/hocs/index.js
> +  return function HOC({ onLoading, ...props }) {
Same here

2019-08-01 22:30 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/screens/Game/components/Moves/index.js
> +  desc: string,
desc and move are required?

2019-08-01 22:30 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/screens/Game/components/Square/index.js
> +  id: number,
Same here

2019-08-01 22:30 UTC, CrisVega08 commented on react/tic-tac-toe/src/app/screens/Podium/index.js
> +import { PLAYER_ONE, PLAYER_TWO } from '~constants/';
If you remove props these constants never use

2019-08-01 22:40 UTC, josepplloo commented on react/tic-tac-toe/src/app/screens/Game/components/Moves/index.js
> +  desc: string,
only move.

2019-08-01 22:42 UTC, josepplloo commented on react/tic-tac-toe/src/app/screens/Game/components/Square/index.js
> +  id: number,
only id

2019-08-01 22:43 UTC, josepplloo commented on react/tic-tac-toe/src/app/screens/Podium/index.js
> +import { PLAYER_ONE, PLAYER_TWO } from '~constants/';
It will use for avoid linter problems with snake case.

2019-08-01 22:58 UTC, CrisVega08 approved these changes

2019-08-01 23:06 UTC, merged